# Generated by Django 3.2.3 on 2021-05-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=20)),
                ('mname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('empid', models.IntegerField(max_length=20)),
                ('address', models.TextField(max_length=400)),
                ('mobile', models.IntegerField(max_length=10)),
                ('position', models.CharField(max_length=20)),
            ],
        ),
    ]
