# Generated by Django 3.2.3 on 2021-05-20 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adv', '0002_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myclass',
            name='img',
        ),
    ]
