# Generated by Django 3.2.3 on 2021-05-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adv', '0003_remove_myclass_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='myclass',
            name='img',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
